require "http"
system "clear"

### Index route 
GET http://localhost:3000/actors.json




### Show route
# GET http://localhost:3000/actors/:id.json
GET http://localhost:3000/actors/17.json

### Create route
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Leonardo", 
  "last_name": "DiCarpio", 
  "known_for": "Titanic"
}

### Update route
#can use PATCH or PUT

PATCH http://localhost:3000/actors/17.json
Content-Type: application/json

{
  "last_name": "DiCaprio"
}


### Destroy route
DELETE http://localhost:3000/actors/17.json


###############################################################
### Index route 
GET http://localhost:3000/movies.json

### Show route
# GET http://localhost:3000/movies/:id.json
GET http://localhost:3000/movies/6.json

### Create route
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "Notting Hill", 
  "year": "1999", 
  "plot": "William Thacker (Hugh Grant) is a London bookstore owner whose humdrum existence is thrown into romantic turmoil when famous American actress Anna Scott (Julia Roberts) appears in his shop. A chance encounter over spilled orange juice leads to a kiss that blossoms into a full-blown affair. As the average bloke and glamorous movie star draw closer and closer together, they struggle to reconcile their radically different lifestyles in the name of love.", "director": "Roger Michell"
}

### Update route
#can use PATCH or PUT

PATCH http://localhost:3000/movies/7.json
Content-Type: application/json

{
  "director": "Howard Zieff"
}


### Destroy route
DELETE http://localhost:3000/movies/8.json



###post request to test actor validations
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "A", 
  "last_name": "K", 
  "known_for": "", 
  "age": 11, 
  "gender": "F"
}


###
PATCH http://localhost:3000/actors/7.json
Content-Type: application/json

{
  "first_name": "A", 
  "last_name": "K", 
  "known_for": "", 
  "age": 11, 
  "gender": "F"
}

###post request to test movie validations
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "",
  "year": "",
  "plot": "",
  "director": ""
}

###
PATCH http://localhost:3000/movies/7.json
Content-Type: application/json

{
  "title": "",
  "year": "",
  "plot": "",
  "director": ""
}


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Claire Dunphy",
  "email": "claire@example.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "claire@example.com",
  "password": "password"
}



### Photos create
POST http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyMDM4MTZ9.lZ0Hf0rX-CvkVCHCVNxlBU_AlUx3OEllqFG8H2jQoSA
Content-Type: application/json

{
  "title": "Uncle Buck",
  "year": "1989",
  "plot": "When Cindy (Elaine Bromka) and her husband, Bob (Garrett M. Brown), have to leave town for a family emergency, there is only one person available to babysit for their three kids: Bob's lazy, carefree brother, Buck (John Candy). While he immediately gets along with the two younger children (Gaby Hoffman, Macaulay Culkin), Buck must change his bachelor lifestyle if he wants to be a responsible caregiver for the angst-filled teenager, Tia (Jean Louisa Kelly).",
  "director": "John Hughes"
}


### Photos create
POST http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyMDUxMDJ9.ERQASxxIP5hc9r6g-wMV8Wd4Ezqr4UIxNLnA86Wsrio
Content-Type: application/json

{
  "title": "The Gold Diggers",
  "year": "1995",
  "plot": "Beth (Christina Ricci) is a city mouse who's just arrived in the country. When her family relocates to a leafy area in the state of Washington, Beth starts hanging out with outsider Jody (Anna Chlumsky), who is constantly regaling Beth with a local legend about a woman named Molly Morgan (Amy Kirk) that supposedly hid a treasure somewhere on nearby Bear Mountain. When the girls decide to tackle Bear Mountain together, Beth learns about the not-so-happy situation Jody is dealing with at home.",
  "director": "Kevin James Dobson"
}