require "http"
system "clear"

response = HTTP.get("http://localhost:3000/movies").parse(:json)
pp response

# response = HTTP.get("http://localhost:3000/movies.json")
# pp response
# ###
# GET http://localhost:3000/movies.json




###

POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Andrew"
}


###
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "id": "4"
}
